### PR TITLE
Move some common batch job code to parent class

### PR DESCRIPTION
**Pull request by nweires**

### CODE REVIEW

**Comment by nweires** [comment]
@lathanh I want to find a way to test this before sending to NREL, but sharing now for any thoughts you have in the meantime.

**Comment by lathanh** [comment]
> @lathanh I want to find a way to test this before sending to NREL, but sharing now for any thoughts you have in the meantime.

If it were me, I'd probably try to use [inversion of control](https://en.wikipedia.org/wiki/Inversion_of_control). That is, rather than have the AWS (and GCP) implementations each responsible for performing the steps, and delegating common implementations to the base class, I'd have the base class responsible for performing the steps, calling on the implementations to do things specific to their implementation. For example, `run_batch()` would be in `docker_base.py`, and it'd call "abstract" methods like `upload_to_weather_files_to_cloud`. This enforces consistency better (defining what the steps are and ensuring they're all performed in in order are in one place, base, rather than two—possibly more in the future).

That said, I'm fine with this as a step forward.

**Comment by nweires** [comment]
> If it were me, I'd probably try to use [inversion of control](https://en.wikipedia.org/wiki/Inversion_of_control)...

Ah, yeah, that would be better!

I'll probably keep these functions or something similar - since they don't do any of the cloud operations, they're better suited to unit tests - but I'll also work on doing what you described. Stay tuned for an updated version of this PR.

**Comment by nweires** [comment]
I moved one section of this to [this PR](https://github.com/NREL/buildstockbatch/pull/415) and added a unit test.

**Pull request closed without merging**
